### ISSUE TITLE
#16887 Bestätigung der Datenschutzhinweise des Kunden als Kommentar in den KS-Ereignissen

### ISSUE THREAD

**Issue by nicolestuck** [drklein-rk/api-drkleinrk#3]
Zurzeit ist es für unsere Finanzierungsberater nicht ersichtlich, ob der Kunde den Datenschutzhinweisen etc. in der Postbank-Leadstrecke zugestimmt hat. Ich habe ein ECON-Ticket erstellt.

**Comment by nicolestuck** [comment]
Ticket #16887 wurde erstellt von Nicole Stuck.

----------------------------------------
Feature #16887: Postbank: Rechtliches und Hinweise
https://agile.intellinet.de/issues/16887

* Autor: Nicole Stuck
* Status: Neu
* Priorität: 1: Jetzt
* Zugewiesen an: Hakan Baran
* Kategorie:
* Zielversion:
* Verantwortlich:
----------------------------------------
Hallo Hakan,

auf dieser Seite der Postbank-Leadstrecke (https://preview-europace.nc.econ-application.de/econ/process/1/postbank-test?) bestätigen die Kunden, wie dir bekannt ist, die Datenschutzhinweise etc.
Diese Information benötigen wir zur Dokumentation und aus Datenschutzgründen auch in den KreditSmart-Ereignissen - also als Kommentar.

Wenn Fragen oder Anmerkungen zu diesem Wunsch bestehen, schreibe mir gerne.

Viele Grüße
Nicole

**Comment by nicolestuck** [comment]
**Edit des Tickets:** 

_Zum Beispiel eingeteilt in 2 Kommentaren:

Kunde hat den Datenschutzhinweisen und der Datenübermittlung an Dr. Klein zugestimmt.

Kunde hat einer Kontaktaufnahme durch Dr. Klein zugestimmt._

**Comment by nicolestuck** [comment]
Ticket #16887 wurde aktualisiert von Hakan Baran.

Status wurde von Neu zu In Bearbeitung geändert
% erledigt wurde von 0 zu 100 geändert

Wie mit Stephan besprochen, wurden alle rechtlichen Hinweise inkl. VVI Download in den Custom-Properties ergänzt.

Testfall in Produktion: DQ1DU1 (Bitte Vorgang nach Prüfung löschen!)

Beste Grüße
Hakan


"partner": {
    "M": {
      "custom": {
        "L": [
          {
            "M": {
              "value": {
                "BOOL": true
              },
              "key": {
                "S": "datenschutz"
              }
            }
          },
          {
            "M": {
              "value": {
                "BOOL": true
              },
              "key": {
                "S": "beratungswunsch"
              }
            }
          },
          {
            "M": {
              "value": {
                "S": "3DFKL"
              },
              "key": {
                "S": "vertriebsschluessel"
              }
            }
          },
          {
            "M": {
              "value": {
                "BOOL": true
              },
              "key": {
                "S": "vvi"
              }
            }
          },
          {
            "M": {
              "value": {
                "BOOL": true
              },
              "key": {
                "S": "datenweitergabe"
              }
            }
          },
          {
            "M": {
              "value": {
                "S": "PB123456"
              },
              "key": {
                "S": "antragsnummer"
              }
            }
          }
        ]
      }
    }
  },

**Comment by SpinGit** [comment]
@nicolestuck Das habe ich umgesetzt gehabt, damit schiebe ich es auf done. Im Postbank Online Geschäft haben wir die Info in KS.
